### ISSUE TITLE
sploit is patched?

### ISSUE THREAD

**Issue by russyboy** [e9x/kru#1]
today when I opened krunker, it says socket error, and if I disabled tampermonkey, it works again.

So I want to know if it is patched?

Thanks

**Comment by russyboy** [comment]
I know that the extension version is discontinued, so should I be supposed to use tampermonkey?

**Comment by e9x** [comment]
Yes, refer to the instructions for installing the userscript.

**Comment by craeckor** [comment]
I have the same Problem, pls FIX

**Comment by russyboy** [comment]
> Yes, refer to the instructions for installing the userscript.

Thanks, sploit is updated.

**Comment by russyboy** [comment]
And is this sploit just for browser?

**Comment by russyboy** [comment]
I see the "client" folder in the package part.

**Comment by e9x** [comment]
The client is for live builds of the source code,  I do not recommend using it but there is no difference between the browser and client scripts.

**Comment by russyboy** [comment]
thanks
