### ISSUE TITLE
Krunker is running

### ISSUE THREAD

**Issue by Janii199** [e9x/kru#2]
It says that Krunker is running but it isn't running. I also can't press the stop button. It won't stop. I tried reinstalling Krunker and the Patcher... nothing worked...
![Unbenannt](https://user-images.githubusercontent.com/84637617/119235197-9440d300-bb31-11eb-84f7-17d59306d5c1.PNG)

**Comment by Janii199** [comment]
i also tried restarting my PC several times

**Comment by e9x** [comment]
Strange, press `Devtools` and click on the console tab then attach a screenshot

**Comment by Janii199** [comment]
![Unbenannt](https://user-images.githubusercontent.com/84637617/119235762-61e4a500-bb34-11eb-828a-fcef6ae2d7d1.PNG)
Like that?

**Comment by e9x** [comment]
Please click this then attach a screenshot
![image](https://user-images.githubusercontent.com/76465669/119235791-321ca980-bb02-11eb-9bac-9e27e3d48d76.png)

**Comment by Janii199** [comment]
![Unbenannt](https://user-images.githubusercontent.com/84637617/119235825-9193ad00-bb34-11eb-814b-5f48f682c149.PNG)

**Comment by e9x** [comment]
Close any apps that are titled "idkr.exe"
